version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fpddd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    command: --skip-name-resolve

volumes:
  mysql-data:
    driver: local
