version: '3.8'

services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fpddd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    command: --skip-name-resolve
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql-data:
    driver: local
